[2025-09-06T12:02:27.434-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-09-06T12:02:27.536-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_FLIGHTS.transform manual__2025-09-06T15:01:43.793153+00:00 [queued]>
[2025-09-06T12:02:27.570-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_FLIGHTS.transform manual__2025-09-06T15:01:43.793153+00:00 [queued]>
[2025-09-06T12:02:27.571-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-09-06T12:02:28.055-0300] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2025-09-06 15:01:43.793153+00:00
[2025-09-06T12:02:28.086-0300] {standard_task_runner.py:63} INFO - Started process 8022 to run task
[2025-09-06T12:02:28.101-0300] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ETL_FLIGHTS', 'transform', 'manual__2025-09-06T15:01:43.793153+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/ETL_FLIGHTS.py', '--cfg-path', '/tmp/tmpctv8f2kw']
[2025-09-06T12:02:28.103-0300] {standard_task_runner.py:91} INFO - Job 31: Subtask transform
[2025-09-06T12:02:28.596-0300] {task_command.py:426} INFO - Running <TaskInstance: ETL_FLIGHTS.transform manual__2025-09-06T15:01:43.793153+00:00 [running]> on host sebastian-Aspire-A515-54
[2025-09-06T12:02:29.375-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='ETL_FLIGHTS' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2025-09-06T15:01:43.793153+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-06T15:01:43.793153+00:00'
[2025-09-06T12:02:29.378-0300] {taskinstance.py:430} INFO - ::endgroup::
[2025-09-06T12:02:30.061-0300] {ETL_FLIGHTS.py:115} INFO - Transform: 86 filas -> 85 filas tras dedup (removidas 1)
[2025-09-06T12:02:30.154-0300] {xcom.py:675} ERROR - Object of type Timestamp is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config or make sure to decorate your object with attr.
[2025-09-06T12:02:30.156-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-09-06T12:02:30.158-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/sebastian/Documentos/Seba/Challenges/Fligoo/.venv/lib/python3.10/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/sebastian/Documentos/Seba/Challenges/Fligoo/.venv/lib/python3.10/site-packages/airflow/serialization/serde.py", line 189, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pandas._libs.tslibs.timestamps.Timestamp'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sebastian/Documentos/Seba/Challenges/Fligoo/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/sebastian/Documentos/Seba/Challenges/Fligoo/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/sebastian/Documentos/Seba/Challenges/Fligoo/.venv/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/sebastian/Documentos/Seba/Challenges/Fligoo/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/sebastian/Documentos/Seba/Challenges/Fligoo/.venv/lib/python3.10/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/sebastian/Documentos/Seba/Challenges/Fligoo/airflow_local/dags/ETL_FLIGHTS.py", line 118, in transform
    ti.xcom_push(key="rows", value=df.to_dict("records"))
  File "/home/sebastian/Documentos/Seba/Challenges/Fligoo/.venv/lib/python3.10/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/sebastian/Documentos/Seba/Challenges/Fligoo/.venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3197, in xcom_push
    XCom.set(
  File "/home/sebastian/Documentos/Seba/Challenges/Fligoo/.venv/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/sebastian/Documentos/Seba/Challenges/Fligoo/.venv/lib/python3.10/site-packages/airflow/models/xcom.py", line 246, in set
    value = cls.serialize_value(
  File "/home/sebastian/Documentos/Seba/Challenges/Fligoo/.venv/lib/python3.10/site-packages/airflow/models/xcom.py", line 673, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/sebastian/Documentos/Seba/Challenges/Fligoo/.venv/lib/python3.10/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/sebastian/Documentos/Seba/Challenges/Fligoo/.venv/lib/python3.10/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Timestamp is not JSON serializable
[2025-09-06T12:02:30.247-0300] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ETL_FLIGHTS, task_id=transform, run_id=manual__2025-09-06T15:01:43.793153+00:00, execution_date=20250906T150143, start_date=20250906T150227, end_date=20250906T150230
[2025-09-06T12:02:30.671-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 31 for task transform (Object of type Timestamp is not JSON serializable; 8022)
[2025-09-06T12:02:30.740-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-09-06T12:02:30.847-0300] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-06T12:02:30.851-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
